/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
/*
Mariam Ehab Mostafa Ahmed
Computer Science Division
*/
/**
 *
 * @author user
 */
public class addmoney extends javax.swing.JFrame {
   
 /**
     * Creates new form addmoney
     */
    public addmoney() {
        initComponents();
       
    }
 

    void addaddmon(ATM atm) {
        confirmadd.addActionListener(atm);
        back.addActionListener(atm);
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addlabel = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        confirmadd = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(598, 448));
        setMinimumSize(new java.awt.Dimension(598, 448));
        setPreferredSize(new java.awt.Dimension(598, 448));
        getContentPane().setLayout(null);

        addlabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        addlabel.setForeground(new java.awt.Color(0, 204, 204));
        addlabel.setText("Enter Amount Of Money To Add:");
        getContentPane().add(addlabel);
        addlabel.setBounds(180, 150, 240, 50);

        ad.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(ad);
        ad.setBounds(210, 200, 180, 40);

        confirmadd.setBackground(new java.awt.Color(0, 204, 204));
        confirmadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirmadd.setText("Confirm");
        confirmadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaddActionPerformed(evt);
            }
        });
        getContentPane().add(confirmadd);
        confirmadd.setBounds(230, 260, 140, 31);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/backk.png"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(100, 340, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/main.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 598, 448);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaddActionPerformed
        
    }//GEN-LAST:event_confirmaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addmoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JLabel addlabel;
    private javax.swing.JButton back;
    private javax.swing.JButton confirmadd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


    public void setAd(JTextField ad) {
        this.ad = ad;
    }

    public void setAddlabel(JLabel addlabel) {
        this.addlabel = addlabel;
    }

    public void setConfirmadd(JButton confirmadd) {
        this.confirmadd = confirmadd;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

  
    public JTextField getAd() {
        return ad;
    }

    public JLabel getAddlabel() {
        return addlabel;
    }

    public JButton getConfirmadd() {
        return confirmadd;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setBack(JButton back) {
        this.back = back;
    }

    public JButton getBack() {
        return back;
    }

    

}
