/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
/*
Mariam Ehab Mostafa Ahmed
Computer Science Division
*/
/**
 *
 * @author user
 */
public class mainaccount extends  javax.swing.JFrame  {
 
    /**
     * Creates new form mainaccount
     */
    public mainaccount() {
        initComponents();
    }
   
 void addMainAcc(ATM atm) {
     addd.addActionListener(atm);
     withdraw.addActionListener(atm);
     amountmoney.addActionListener(atm);
     account.addActionListener(atm);
     last5trans.addActionListener(atm);
     logout.addActionListener(atm);
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
  

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amountmoney = new javax.swing.JButton();
        addd = new javax.swing.JButton();
        last5trans = new javax.swing.JButton();
        withdraw = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        account = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(598, 448));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Eltorky");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 150, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Bank");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 210, 110, 40);

        amountmoney.setBackground(new java.awt.Color(0, 204, 204));
        amountmoney.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        amountmoney.setText("Available Amount Of Money");
        amountmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountmoneyActionPerformed(evt);
            }
        });
        getContentPane().add(amountmoney);
        amountmoney.setBounds(307, 270, 223, 60);

        addd.setBackground(new java.awt.Color(0, 204, 204));
        addd.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        addd.setText("Add");
        addd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddActionPerformed(evt);
            }
        });
        getContentPane().add(addd);
        addd.setBounds(70, 90, 80, 60);

        last5trans.setBackground(new java.awt.Color(0, 204, 204));
        last5trans.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        last5trans.setText("Last 5 \ntransactions");
        last5trans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last5transActionPerformed(evt);
            }
        });
        getContentPane().add(last5trans);
        last5trans.setBounds(360, 210, 170, 60);

        withdraw.setBackground(new java.awt.Color(0, 204, 204));
        withdraw.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        withdraw.setText("Withdraw");
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw);
        withdraw.setBounds(70, 150, 120, 60);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/exitt.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(470, 70, 50, 40);

        account.setBackground(new java.awt.Color(0, 204, 204));
        account.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        account.setText("My Account");
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });
        getContentPane().add(account);
        account.setBounds(80, 320, 140, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/main.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountmoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountmoneyActionPerformed

    private void adddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddActionPerformed
        
    }//GEN-LAST:event_adddActionPerformed

    private void last5transActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last5transActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last5transActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainaccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account;
    private javax.swing.JButton addd;
    private javax.swing.JButton amountmoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton last5trans;
    private javax.swing.JButton logout;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables

  

    public void setAccount(JButton account) {
        this.account = account;
    }

 

    public void setAmountmoney(JButton amountmoney) {
        this.amountmoney = amountmoney;
    }

  

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

   

    public void setLast5trans(JButton last5trans) {
        this.last5trans = last5trans;
    }

    public void setLogout(JButton logout) {
        this.logout = logout;
    }

    public void setWithdraw(JButton withdraw) {
        this.withdraw = withdraw;
    }

   
    public JButton getAccount() {
        return account;
    }


    public JButton getAmountmoney() {
        return amountmoney;
    }

  

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

   

    public JButton getLast5trans() {
        return last5trans;
    }

    public JButton getLogout() {
        return logout;
    }

    public JButton getWithdraw() {
        return withdraw;
    }

    public  JButton getAddd() {
        return addd;
    }

    public void setAddd(JButton addd) {
        this.addd = addd;
    }

   

}

