/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;
import com.sun.security.ntlm.Client;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
/*
Mariam Ehab Mostafa Ahmed
Computer Science Division
*/
/**
 *
 * @author user
 */

public class main extends javax.swing.JFrame   {
   
  
    String numbers=new String();
     String numbers1=new String();
     int ac=0;
 
    /**
     * Creates new form main
     */
   
   
    public void setNumbers(String numbers) {
        this.numbers = numbers;
    }

    public void setNumbers1(String numbers1) {
        this.numbers1 = numbers1;
    }

    public String getNumbers() {
        return numbers;
    }

    public String getNumbers1() {
        return numbers1;
    }

    public void setAc(int ac) {
        this.ac = ac;
    }

    public int getAc() {
        return ac;
    }

  

    

  
    public main() {
    initComponents();
    }
   
     void addATM(ActionListener atm) {
        
        login.addActionListener(atm);
        one.addActionListener(atm);
        two.addActionListener(atm);
        three.addActionListener(atm);
        four.addActionListener(atm);
        five.addActionListener(atm);
        six.addActionListener(atm);
        seven.addActionListener(atm);
        eight.addActionListener(atm);
        nine.addActionListener(atm);
        zero.addActionListener(atm);
        
     
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void addFoucs(FocusListener atm) {

    accountno.addFocusListener(atm);
        password.addFocusListener(atm);
    
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        accountno = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        three = new javax.swing.JButton();
        one = new javax.swing.JButton();
        four = new javax.swing.JButton();
        six = new javax.swing.JButton();
        two = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        five = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        login = new javax.swing.JButton();
        passwordlabel = new javax.swing.JLabel();
        usernamelabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(610, 460));
        setMinimumSize(new java.awt.Dimension(610, 460));
        setSize(new java.awt.Dimension(610, 460));
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Tekton Pro Ext", 1, 33)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Welcome To Eltorky Bank");
        title.setAlignmentY(0.6F);
        getContentPane().add(title);
        title.setBounds(80, 70, 440, 60);

        accountno.setToolTipText("");
        accountno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accountnoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountnoFocusLost(evt);
            }
        });
        accountno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountnoMouseClicked(evt);
            }
        });
        accountno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountnoActionPerformed(evt);
            }
        });
        accountno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                accountnoKeyPressed(evt);
            }
        });
        getContentPane().add(accountno);
        accountno.setBounds(210, 160, 180, 30);

        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(210, 210, 180, 30);

        three.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three);
        three.setBounds(210, 260, 50, 23);

        one.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one);
        one.setBounds(90, 260, 50, 23);

        four.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four);
        four.setBounds(90, 290, 50, 23);

        six.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six);
        six.setBounds(210, 290, 50, 23);

        two.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two);
        two.setBounds(150, 260, 50, 23);

        zero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero);
        zero.setBounds(150, 350, 50, 23);

        eight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight);
        eight.setBounds(150, 320, 50, 23);

        nine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine);
        nine.setBounds(210, 320, 50, 23);

        five.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five);
        five.setBounds(150, 290, 50, 23);

        seven.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven);
        seven.setBounds(90, 320, 50, 23);

        login.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(330, 280, 120, 50);

        passwordlabel.setFont(new java.awt.Font("Vodafone ExB", 0, 18)); // NOI18N
        passwordlabel.setForeground(java.awt.SystemColor.activeCaption);
        passwordlabel.setText("Password");
        getContentPane().add(passwordlabel);
        passwordlabel.setBounds(90, 210, 90, 20);

        usernamelabel.setFont(new java.awt.Font("Vodafone ExB", 0, 16)); // NOI18N
        usernamelabel.setForeground(java.awt.SystemColor.activeCaption);
        usernamelabel.setText("Account Number");
        getContentPane().add(usernamelabel);
        usernamelabel.setBounds(80, 160, 120, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/main.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountnoActionPerformed
     
    }//GEN-LAST:event_accountnoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed

    }//GEN-LAST:event_threeActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed

    }//GEN-LAST:event_oneActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
     
    }//GEN-LAST:event_fourActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        
    }//GEN-LAST:event_sixActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
         
    }//GEN-LAST:event_twoActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        
    }//GEN-LAST:event_zeroActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
       
    }//GEN-LAST:event_nineActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
          
    }//GEN-LAST:event_fiveActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
    }//GEN-LAST:event_loginActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        
    }//GEN-LAST:event_sevenActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        
    }//GEN-LAST:event_passwordActionPerformed

    private void accountnoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountnoFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_accountnoFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFocusGained

    private void accountnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountnoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_accountnoFocusLost

    private void accountnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accountnoKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_accountnoKeyPressed

    private void accountnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountnoMouseClicked
          
    }//GEN-LAST:event_accountnoMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked

             
    }//GEN-LAST:event_passwordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountno;
    private javax.swing.JButton eight;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordlabel;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton three;
    private javax.swing.JLabel title;
    private javax.swing.JButton two;
    private javax.swing.JLabel usernamelabel;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables

  

    public JTextField getaccountno() {
        return accountno;
    }

    public JButton getEight() {
        return eight;
    }

    public JButton getFive() {
        return five;
    }

    public JButton getFour() {
        return four;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JButton getLogin() {
        return login;
    }

    
 
    public void setaccountno(JTextField accountno) {
        this.accountno = accountno;
    }

    public void setEight(JButton eight) {
        this.eight = eight;
    }

    public void setFive(JButton five) {
        this.five = five;
    }

    public void setFour(JButton four) {
        this.four = four;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setLogin(JButton login) {
        this.login = login;
    }

    public void setNine(JButton nine) {
        this.nine = nine;
    }

    public void setOne(JButton one) {
        this.one = one;
    }

    public void setPassword(JPasswordField password) {
        this.password = password;
    }

    public void setPasswordlabel(JLabel passwordlabel) {
        this.passwordlabel = passwordlabel;
    }

    public void setSeven(JButton seven) {
        this.seven = seven;
    }

    public void setSix(JButton six) {
        this.six = six;
    }

    public void setThree(JButton three) {
        this.three = three;
    }

    public void setTitle(JLabel title) {
        this.title = title;
    }

    public void setTwo(JButton two) {
        this.two = two;
    }

    public void setUsernamelabel(JLabel usernamelabel) {
        this.usernamelabel = usernamelabel;
    }

    public void setZero(JButton zero) {
        this.zero = zero;
    }

    public JButton getNine() {
        return nine;
    }

    public JButton getOne() {
        return one;
    }

    public JPasswordField getPassword() {
        return password;
    }

    public JLabel getPasswordlabel() {
        return passwordlabel;
    }

    public JButton getSeven() {
        return seven;
    }

    public JButton getSix() {
        return six;
    }

    public JButton getThree() {
        return three;
    }

 

    public JButton getTwo() {
        return two;
    }

    public JLabel getUsernamelabel() {
        return usernamelabel;
    }

    public JButton getZero() {
        return zero;
    }

    public void setAccountno(JTextField accountno) {
        this.accountno = accountno;
    }

    public JTextField getAccountno() {
        return accountno;
    }

}
    

   
    

