/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
/*
Mariam Ehab Mostafa Ahmed
Computer Science Division
*/
/**
 *
 * @author user
 */
public class withdrawmoney extends javax.swing.JFrame {

    /**
     * Creates new form withdrawmoney
     */
    public withdrawmoney() {
        initComponents();
    }
      void withwithmon(ATM atm) {
          confirmwithd.addActionListener(atm);
          back.addActionListener(atm);
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        withd = new javax.swing.JTextField();
        confirmwithd = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(598, 448));
        setMinimumSize(new java.awt.Dimension(598, 448));
        setPreferredSize(new java.awt.Dimension(598, 448));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Enter Amount Of Money To withdraw:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 150, 240, 50);

        withd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(withd);
        withd.setBounds(210, 200, 180, 40);

        confirmwithd.setBackground(new java.awt.Color(0, 204, 204));
        confirmwithd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        confirmwithd.setText("Confirm");
        getContentPane().add(confirmwithd);
        confirmwithd.setBounds(230, 260, 140, 31);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/backk.png"))); // NOI18N
        getContentPane().add(back);
        back.setBounds(100, 340, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/pictures/main.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 598, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdrawmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdrawmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdrawmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdrawmoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdrawmoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirmwithd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField withd;
    // End of variables declaration//GEN-END:variables

    public void setConfirmwithd(JButton confirmwithd) {
        this.confirmwithd = confirmwithd;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public void setWithd(JTextField withd) {
        this.withd = withd;
    }

    public JButton getConfirmwithd() {
        return confirmwithd;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JTextField getWithd() {
        return withd;
    }

    public void setBack(JButton back) {
        this.back = back;
    }

    public JButton getBack() {
        return back;
    }
    

  

  
}
